import datetime, io, json, os
LOG = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'log.jsonl')
ts = datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
base = dict(stage='planner', provider='claude', model='opus', effort='medium')
R, S = 'crates/cctg/src/hub/registry.rs', 'crates/cctg/src/hub/slots.rs'
entries = [
 ('decision', "Registry is pure (no IO, no async) and owned by one Slots actor; every Telegram answer returns as a Done message on the actor's own channel, so ingress keeps draining during retry_after. Alternative: Arc<Mutex<Registry>> with Telegram awaited inline on the ingress loop (the TASK-010 QA failure mode).", [R, S]),
 ('decision', "Topic calls come from one diff, Registry::topic_work: desired title/icon vs applied_title/applied_icon per slot, busy flag per slot, failed marker until retry_every. Alternative: each event emits its own create/edit effects (duplicate edits, harder to guarantee exactly one replacement after TOPIC_ID_INVALID).", [R]),
 ('decision', "Nesting is decided on the hub from the existing wire field HookEvent::SessionStart.parent_claude_pid plus a persisted pids map '<host>/<claude_pid>' -> session_id: unknown pid = Nested{parent: None}, pid of the session itself = TopLevel. No wire change; TASK-012 only fills claude_pid/parent_claude_pid. Alternative: the device sends a nesting enum or parent session id (needs the hub registry on the device anyway, bumps the contract).", [R, 'crates/cctg/src/wire.rs']),
 ('decision', "No separator for the first session of a brand-new slot; a separator only when a slot's current session changes to another id. Alternative: separator on every occupancy (acceptance 1 would see two separators in the topic).", [R]),
 ('decision', "Slot allocation order: slot the session already holds; its previous slot if free (resume keeps the topic); slot of the previous session of the same host+claude_pid in the same folder (/clear), which that session gives up; first free ordinal; new ordinal. Alternative: plain first-free (a /clear or resume can jump to another topic).", [R]),
 ('decision', "An unparsable or foreign-version registry.json stops `cctg hub` with a fixed-text error; a missing file is an empty registry. Alternative: start empty (every folder silently gets a second topic).", [R, 'crates/cctg/src/hub/mod.rs']),
 ('decision', "After start, topic edits wait a 45 s grace (> agent max backoff 30 s) while creations and separators go out at once. Alternative: edit immediately (every live slot flips to no-channel and back after each hub restart, plus two service messages each).", [S]),
 ('decision', "An agent whose session the registry does not know waits hook_wait=10 s for its SessionStart hook, then the session is adopted as top-level; UserPromptSubmit/Stop of an unknown session also adopt it. Alternative: never give agent-only sessions a slot (a session started while the hub was down would stay invisible, contradicting TASK-018).", [S, R]),
 ('decision', "Every forum_topic_edited service message whose thread is a slot topic is deleted; nothing is deleted when the bot lacks can_delete_messages (startup warning is the one log), and the first runtime delete failure warns once. Alternative: count expected edits per topic and delete only those (fragile when an edit's service message is lost or reordered).", [S, 'crates/cctg/src/hub/mod.rs']),
 ('decision', "Icons alive/dead/waiting/no_channel = 5312016608254762256 (lightning) / 5408906741125490282 (chequered flag) / 5377316857231450742 (question mark) / 5357121491508928442 (eyes) from a read-only getForumTopicIconStickers call (112 stickers, 2026-09-23); the hub re-checks them at start and drops any id Telegram no longer offers. Alternative: env-configurable ids (a knob nobody asked for).", [R, 'maw/tasks/in_progress/TASK-011/scratch/planner/icon_stickers.json']),
 ('decision', "Title limit 128 is measured with transcript::telegram_len (UTF-16 units, >= chars); label cut first, then folder, host capped at 32, ' #N' always kept. Alternative: chars().count() (an emoji title could exceed Telegram's count).", [R]),
 ('decision', "SlotLocator answers /brief and /full in a slot topic without a prefix from the registry view (watch channel); General, prefixes and unknown topics keep ProjectsDir. New LocateError::NoTranscript for an agent-only session. Alternative: registry-only locator (breaks /brief in General and prefix lookups of pre-registry sessions).", ['crates/cctg/src/hub/sessions.rs']),
 ('dead_end', "First slots actor tests sent a hook and an agent registration back to back and expected hook-first order; tokio::select! picks among ready channels at random, so the agent was sometimes handled first (pending, then bound) and the op count differed. Tests now wait for the hook's op before sending the agent; production relies on the pending/hook_wait path for exactly this reorder.", [S]),
 ('dead_end', "Mutation 'separator for the first session of a new slot' survives: topic_created clears pending_separator, so the mutant is behaviourally equivalent; no test can kill it.", [R, 'maw/tasks/in_progress/TASK-011/scratch/planner/mutations.out.txt']),
]
with io.open(LOG, 'a', encoding='utf-8', newline='\n') as f:
    for kind, body, refs in entries:
        f.write(json.dumps(dict(ts=ts, **base, kind=kind, body=body, refs=refs), ensure_ascii=False) + '\n')
print('appended', len(entries))
