import datetime, io, json, os
LOG = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'log.jsonl')
ts = datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
base = dict(stage='planner', provider='claude', model='opus', effort='medium')
P = 'maw/tasks/in_progress/TASK-016/scratch/planner/'
S, H, C, T, W = ('crates/cctg/src/hub/slots.rs', 'crates/cctg/src/hub/stream.rs',
                 'crates/cctg/src/hub/scheduler.rs', 'crates/cctg/src/tail.rs', 'crates/cctg/src/wire.rs')
entries = [
 ('decision', "Tool-call lines come from the transcript read by the session agent (option a), no PreToolUse/PostToolUse hooks. Measured: records become visible 0.1-0.3 s after their timestamp (claude -p median ~0.13 s; live interactive subagent transcript median 0.16 s, max 0.28 s); in an interactive main transcript the assistant record (text + tool_use) is only written when the tool finishes (4.6-6.6 s lag on a 3 s tool, the user's 4-7 s), but the tool_result right after it is visible 0.10-0.19 s after the tool ends, so a finished-call line is as timely as a PostToolUse hook. Hook cost per tool call: ~17-19 ms with a live hub, ~530 ms with the hub down (dev build, Windows). Alternative: PostToolUse hook for the instant line plus transcript for history (a process per tool call, 0.5 s stall per call when the hub is down, same moment).", [P + 'lag_probe.i3.out.txt', P + 'lag_probe.run1.out.txt', P + 'passive_lag.interactive-subagent.out.txt', P + 'hook_cost.out.txt']),
 ('decision', "The hub owns the stream offset (registry sessions[..].stream.offset = transcript bytes whose messages Telegram has answered, plus pending tool calls and 👀 receipts); the agent is stateless and answers each hub transcript_read {session_id, path, from} with one transcript_chunk of complete lines as transcript::stream_events. A hub restart re-reads from the answered offset (at most the messages in flight repeat), an agent restart (resume) is served from the same offset. Alternative: agent-owned offsets pushed continuously (needs an ack protocol and state across agent processes; a new agent after /resume would not know it).", [S, H, T, W]),
 ('decision', "✍ evidence is the session's own transcript: a meta user record (or a queued_command attachment) whose <channel ...> opening tag has message_id=N, for an N the hub handed to that session's agent (receipts, persisted, 32 max). UserPromptSubmit is not used for reactions at all. Alternative: a UserPromptSubmit hook that extracts message_id from the prompt (unverified that it fires for channel messages; a second parser of the channel tag in the hook).", [H, 'crates/transcript/src/stream.rs']),
 ('decision', "Merging of tool-call lines lives in the scheduler: Op::Stream{merge:true} lines of one topic queued behind the head line join its message only when more messages wait than the bucket has tokens, never across another message of that topic, within 4096 UTF-16 units; merged jobs answer Outcome::Merged. Permission prompts overtake stream lines of their own topic (not ordinary messages). Alternative: batching in the slots actor (it cannot see the bucket or the queue).", [C]),
 ('decision', "A Stop answer of a streamed session is held until the chunk of the first transcript read issued after the Stop is handed out (max Options.hold_answer 1.5 s), so the turn's last tool lines come before the answer. Alternative: send at once (the last line can land after the answer when the answer follows the last tool result within one poll interval, 300 ms).", [S]),
 ('decision', "Terminal-typed prompts and slash commands stream as '> text' (brief form); Telegram-originated prompts are not echoed (only reactions). Assistant text streams only with stop_reason tool_use; end_turn/null text is left to the Stop hook. Alternative: tool lines only (the Telegram reader sees answers to prompts it never saw).", ['crates/transcript/src/stream.rs']),
]
with io.open(LOG, 'a', encoding='utf-8', newline='\n') as f:
    for kind, body, refs in entries:
        f.write(json.dumps(dict(ts=ts, **base, kind=kind, body=body, refs=refs), ensure_ascii=False) + '\n')
print('appended', len(entries))
