import datetime, io, json, os
LOG = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'log.jsonl')
ts = datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')
base = dict(stage='plan-reviewer-2', provider='claude', model='opus', effort='medium')
P = 'maw/tasks/in_progress/TASK-016/scratch/reviewer2/'
S, H, C, T, X, A = ('crates/cctg/src/hub/slots.rs', 'crates/cctg/src/hub/stream.rs',
                    'crates/cctg/src/hub/scheduler.rs', 'crates/cctg/src/tail.rs',
                    'crates/transcript/src/stream.rs', 'crates/cctg/src/agent.rs')
entries = [
 ('decision', "Call order: open tool calls are kept in call order (persisted Stream.calls); a result marks its call done and only the done calls at the head are sent, so Result(B) before Result(A) waits for A. A prompt, a note or a turn end flushes the turn (done calls in call order, calls without a result are not shown); a call past MAX_CALLS=64 lets the oldest go the same way. Alternative: PLAN_V2's 'stop read-ahead at the cap' (deadlocks: the flush marker is further in the file than the stopped read).", [H]),
 ('decision', "Offset commit: every read ends with a barrier (offset + snapshot of open calls); it is persisted only when every stream message before it was answered Sent/Merged. A refused message (network, 5xx, lost topic) stops commits; once nothing is in flight the stream rewinds to the last committed barrier after Options.stream_retry (5 s), so order holds and lines come at least once. A 4xx that is not a lost topic is skipped with one warning (a message Telegram never takes must not block the stream). The scheduler answers Merged only after the merged send succeeded, otherwise the merged receivers close. Alternative: retry the single failed job (later lines already queued would overtake it).", [S, H, C]),
 ('decision', "Stop barrier: transcript::stream_events emits TurnEnd for an assistant text record whose stop_reason is set and not tool_use (the thinking record of the same response has no text block, so one TurnEnd per final text). A Stop of a streamed session is held in a FIFO (max 8) until a TurnEnd is read, then goes after the lines before it; a TurnEnd read before its Stop is counted (ends_unclaimed, cleared by a new prompt or a matched channel record) and lets that Stop go at once; a blank Stop still takes its turn end; Options.hold_answer (5 s) bounds the wait. Alternatives: prompt_id correlation (assistant records carry no promptId; Stop.prompt_id unverified), PLAN.md's first-read-after-Stop with 1.5 s (lets late tool lines follow the answer).", [S, X]),
 ('dead_end', "Finding 4 (tool errors shown as ✓ when is_error is absent) not reproduced: 9,661 real tool_result blocks in the 400 newest local transcripts; every <tool_use_error> (10) and every string toolUseResult starting 'Error:' or 'User rejected' (313) has is_error: true; is_error is absent only on tool_reference results (ToolSearch) and MCP results, where treating 'Error' text or a string toolUseResult as failure would mark successful MCP calls ✗. Code left as is (is_error == true).", [X]),
 ('decision', "Path gate: the agent reads only a file whose canonical path is <canonical root>/<one dir>/<session_id>.jsonl with root = CLAUDE_CONFIG_DIR/projects, else USERPROFILE|HOME/.claude/projects, and that is a regular file; missing or foreign = missing. Replacement/truncation: a read from offset N answers reset when N > len or byte N-1 is not a newline; the hub warns once and reads from 0 (repeat possible, no loss). Alternative: file identity (windows-sys file id / dev+ino) plus a 4 KiB checkpoint (platform code for a case Claude Code never produces).", [T]),
 ('dead_end', "Request ids on transcript_read/chunk not added: a late chunk of a timed-out read carries `from`, and the hub accepts a chunk only when from == read_at and it comes on the connection the read went to (added), so a stale answer is either still a valid read of the same bytes or dropped.", [S]),
 ('decision', "Agent reads are serialized: one reader task per agent process with a request slot of 1; the channel loop try_sends and drops a request while one waits (the hub asks again after 10 s or on a new connection), so there is at most one blocking read and one queued. Stream messages count in queued_messages and the stream takes no new line while 128 (MAX_QUEUED_MESSAGES/2) wait or 64 of its own do (the rest stays in the file); reactions are capped at 64 in flight. Alternative: per-request spawn_blocking (unbounded blocking reads on timeouts).", [A, S]),
]
with io.open(LOG, 'a', encoding='utf-8', newline='\n') as f:
    for kind, body, refs in entries:
        f.write(json.dumps(dict(ts=ts, **base, kind=kind, body=body, refs=refs), ensure_ascii=False) + '\n')
print('appended', len(entries))
